# Generated by Django 5.1.3 on 2024-11-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsplit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='billdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='billname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
