# Generated by Django 5.1.3 on 2024-11-11 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0005_alter_expenses_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="time",
            field=models.TimeField(default=datetime.time(20, 26, 57, 481428)),
        ),
    ]
