# Generated by Django 5.1.2 on 2024-10-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("password", models.CharField(max_length=8)),
                ("otp", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="emailotp",
            options={},
        ),
    ]
