# Generated by Django 5.1.3 on 2024-11-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0005_alter_register_user_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact", models.CharField(max_length=10, unique=True)),
                ("otp", models.IntegerField(blank=True, null=True)),
                ("otp_created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="appassword",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="contact",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="currency",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="monthlylimit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
