# Generated by Django 5.1.3 on 2024-11-22 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triptracker', '0002_tosettle_connect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tosettle',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='triptracker.tripgroup'),
        ),
    ]
