# Generated by Django 5.1.3 on 2024-11-27 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triptracker', '0004_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='time',
            field=models.TimeField(default=datetime.time(11, 46, 1, 590746)),
        ),
    ]
